# Generated by Django 2.0.2 on 2018-05-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('space', models.IntegerField()),
                ('introduction', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='meetingApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32)),
                ('attendance', models.IntegerField()),
                ('beginTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('day', models.DateField()),
                ('applytime', models.DateTimeField(auto_now_add=True)),
                ('homeID', models.ForeignKey(on_delete=True, to='user.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingApplyStaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('day', models.DateField()),
                ('location', models.ForeignKey(on_delete=True, to='user.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('realname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='meetingapply',
            name='statusID',
            field=models.ForeignKey(on_delete=True, to='user.MeetingApplyStaus'),
        ),
        migrations.AddField(
            model_name='meetingapply',
            name='workerID',
            field=models.ForeignKey(on_delete=True, to='user.User'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.ForeignKey(on_delete=True, to='user.Classroom_status'),
        ),
    ]
