# Generated by Django 2.0.2 on 2018-05-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_meetingapply_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingapply',
            name='day',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
